/*
 * cdg
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cdg_client

type LcaInternalPkgDtoRunDto struct {
	CollectionId string `json:"collectionId,omitempty"`
	Error_ string `json:"error,omitempty"`
	RunId string `json:"runId,omitempty"`
	Status string `json:"status,omitempty"`
}
