/*
 * cdg
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cdg_client

type LcaInternalPkgDtoCollectionDto struct {
	Error_ string `json:"error"`
	Host string `json:"host,omitempty"`
	Id string `json:"id,omitempty"`
	Password string `json:"password,omitempty"`
	Path string `json:"path"`
	Port int32 `json:"port,omitempty"`
	Script string `json:"script,omitempty"`
	Status string `json:"status"`
	User string `json:"user,omitempty"`
}
