/*
 * cdg
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cdg_client

type LcaInternalPkgDtoCollectionDto struct {
	CollectionId string `json:"collectionId,omitempty"`
	Go_ *LcaInternalPkgEventsGoInfo `json:"go,omitempty"`
	Runs []LcaInternalPkgDtoRunDto `json:"runs,omitempty"`
	Ssh *LcaInternalPkgEventsSshInfo `json:"ssh,omitempty"`
	Type_ string `json:"type,omitempty"`
}
