/*
 * cdg
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cdg_client

type LcaInternalAppCdgCollectionItem struct {
	Id string `json:"id,omitempty"`
	Ip string `json:"ip,omitempty"`
	Password string `json:"password,omitempty"`
	Port int32 `json:"port,omitempty"`
	Script string `json:"script,omitempty"`
	Status string `json:"status,omitempty"`
	User string `json:"user,omitempty"`
}
