/*
 * cdg
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cdg_client

type LcaInternalPkgEventsSshInfo struct {
	Host string `json:"host,omitempty"`
	Password string `json:"password,omitempty"`
	Port int32 `json:"port,omitempty"`
	Script string `json:"script,omitempty"`
	Timeout int64 `json:"timeout,omitempty"`
	User string `json:"user,omitempty"`
}
