/*
 * scheduler
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package scheduler_client

type LcaInternalPkgDtoRunScheduleDto struct {
	CollectionId string `json:"collectionId,omitempty"`
	RunId string `json:"runId,omitempty"`
}
