/*
 * scheduler
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package scheduler_client

type LcaInternalPkgDtoScheduleSshCollectionDto struct {
	// cron for repeat collection - leave empty if one off
	Cron string `json:"cron,omitempty"`
	Repeat bool `json:"repeat,omitempty"`
	Script string `json:"script"`
	Targets []LcaInternalPkgDtoTargetDto `json:"targets"`
	Timeout string `json:"timeout"`
}
