services:
  scheduler:
    container_name: scheduler
    image: "scheduler:latest"
    ports:
      - "8080:8080"
    restart: always

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

  dummy-ssh-ne1:
    container_name: ne1
    image: "ssh-host:latest"
    ports:
      - "2222:22"
    restart: always
    environment:
      SSH_USERS: "nesshuser:1000:1000:nesshpass"
      SSH_ENABLE_PASSWORD_AUTH: "true"
      SSH_ENABLE_ROOT_PASSWORD_AUTH: "true"
