services:
  scheduler:
    container_name: scheduler
    image: "scheduler:latest"
    ports:
      - "8080:8080"
    restart: always

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

  dummy-ssh-ne1:
    container_name: ne1
    image: "ssh-host:latest"
    ports:
      - "2222:22"
    restart: always
    entrypoint: sleep 10000
    environment:
      SSH_USERS: "nesshuser:1000:1000:nesshpass"
      SSH_ENABLE_PASSWORD_AUTH: "true"
      SSH_ENABLE_ROOT_PASSWORD_AUTH: "true"

  collectiondatagateway:
    container_name: collectiondatagateway
    image: "collectiondatagateway:latest"
    ports:
      - "5555:5555"
    restart: always
    environment:
      - COLLECTION_DATA_GATEWAY_HOST=collectiondatagateway
      - COLLECTION_DATA_GATEWAY_PORT=5555
      - COLLECTION_DATA_GATEWAY_BASE_PATH = /api/v1
