apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - name: web
      protocol: TCP
      port: 3004
      targetPort: 3004
      nodePort: 30040