apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: lca-web
          imagePullPolicy: Never
          resources:
            limits:
              memory: 512Mi
              cpu: "500m"
          env:
          - name: APP_NAME
            value: web
          - name: APP_VERSION
            value: "0.1.0"
          - name: APP_DATA_PATH
            value: " "
          - name: PORT
            value: "3004"
          - name: RMQ_URI
            value: amqp://rabbitmq:5672
          - name: DB_CONNECTION
            value: " "