apiVersion: v1
kind: Service
metadata:
  name: scheduler
spec:
  type: NodePort
  selector:
    app: scheduler
  ports:
    - name: scheduler
      protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30010