// Code generated by counterfeiter. DO NOT EDIT.
package sshfakes

import (
	"lca/internal/pkg/ssh"
	"sync"
)

type FakeSSHOptions struct {
	GetAddressStub        func() string
	getAddressMutex       sync.RWMutex
	getAddressArgsForCall []struct {
	}
	getAddressReturns struct {
		result1 string
	}
	getAddressReturnsOnCall map[int]struct {
		result1 string
	}
	GetCredentialsStub        func() (string, string)
	getCredentialsMutex       sync.RWMutex
	getCredentialsArgsForCall []struct {
	}
	getCredentialsReturns struct {
		result1 string
		result2 string
	}
	getCredentialsReturnsOnCall map[int]struct {
		result1 string
		result2 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSSHOptions) GetAddress() string {
	fake.getAddressMutex.Lock()
	ret, specificReturn := fake.getAddressReturnsOnCall[len(fake.getAddressArgsForCall)]
	fake.getAddressArgsForCall = append(fake.getAddressArgsForCall, struct {
	}{})
	stub := fake.GetAddressStub
	fakeReturns := fake.getAddressReturns
	fake.recordInvocation("GetAddress", []interface{}{})
	fake.getAddressMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSSHOptions) GetAddressCallCount() int {
	fake.getAddressMutex.RLock()
	defer fake.getAddressMutex.RUnlock()
	return len(fake.getAddressArgsForCall)
}

func (fake *FakeSSHOptions) GetAddressCalls(stub func() string) {
	fake.getAddressMutex.Lock()
	defer fake.getAddressMutex.Unlock()
	fake.GetAddressStub = stub
}

func (fake *FakeSSHOptions) GetAddressReturns(result1 string) {
	fake.getAddressMutex.Lock()
	defer fake.getAddressMutex.Unlock()
	fake.GetAddressStub = nil
	fake.getAddressReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeSSHOptions) GetAddressReturnsOnCall(i int, result1 string) {
	fake.getAddressMutex.Lock()
	defer fake.getAddressMutex.Unlock()
	fake.GetAddressStub = nil
	if fake.getAddressReturnsOnCall == nil {
		fake.getAddressReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.getAddressReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeSSHOptions) GetCredentials() (string, string) {
	fake.getCredentialsMutex.Lock()
	ret, specificReturn := fake.getCredentialsReturnsOnCall[len(fake.getCredentialsArgsForCall)]
	fake.getCredentialsArgsForCall = append(fake.getCredentialsArgsForCall, struct {
	}{})
	stub := fake.GetCredentialsStub
	fakeReturns := fake.getCredentialsReturns
	fake.recordInvocation("GetCredentials", []interface{}{})
	fake.getCredentialsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSSHOptions) GetCredentialsCallCount() int {
	fake.getCredentialsMutex.RLock()
	defer fake.getCredentialsMutex.RUnlock()
	return len(fake.getCredentialsArgsForCall)
}

func (fake *FakeSSHOptions) GetCredentialsCalls(stub func() (string, string)) {
	fake.getCredentialsMutex.Lock()
	defer fake.getCredentialsMutex.Unlock()
	fake.GetCredentialsStub = stub
}

func (fake *FakeSSHOptions) GetCredentialsReturns(result1 string, result2 string) {
	fake.getCredentialsMutex.Lock()
	defer fake.getCredentialsMutex.Unlock()
	fake.GetCredentialsStub = nil
	fake.getCredentialsReturns = struct {
		result1 string
		result2 string
	}{result1, result2}
}

func (fake *FakeSSHOptions) GetCredentialsReturnsOnCall(i int, result1 string, result2 string) {
	fake.getCredentialsMutex.Lock()
	defer fake.getCredentialsMutex.Unlock()
	fake.GetCredentialsStub = nil
	if fake.getCredentialsReturnsOnCall == nil {
		fake.getCredentialsReturnsOnCall = make(map[int]struct {
			result1 string
			result2 string
		})
	}
	fake.getCredentialsReturnsOnCall[i] = struct {
		result1 string
		result2 string
	}{result1, result2}
}

func (fake *FakeSSHOptions) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getAddressMutex.RLock()
	defer fake.getAddressMutex.RUnlock()
	fake.getCredentialsMutex.RLock()
	defer fake.getCredentialsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSSHOptions) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ ssh.SSHOptions = new(FakeSSHOptions)
