// Code generated by counterfeiter. DO NOT EDIT.
package collectorfakes

import (
	"context"
	"lca/internal/app/collector"
	"sync"
)

type FakeCollectionRunner struct {
	RunStub        func(context.Context, collector.JobData, collector.CollectionRunnerOptions)
	runMutex       sync.RWMutex
	runArgsForCall []struct {
		arg1 context.Context
		arg2 collector.JobData
		arg3 collector.CollectionRunnerOptions
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCollectionRunner) Run(arg1 context.Context, arg2 collector.JobData, arg3 collector.CollectionRunnerOptions) {
	fake.runMutex.Lock()
	fake.runArgsForCall = append(fake.runArgsForCall, struct {
		arg1 context.Context
		arg2 collector.JobData
		arg3 collector.CollectionRunnerOptions
	}{arg1, arg2, arg3})
	stub := fake.RunStub
	fake.recordInvocation("Run", []interface{}{arg1, arg2, arg3})
	fake.runMutex.Unlock()
	if stub != nil {
		fake.RunStub(arg1, arg2, arg3)
	}
}

func (fake *FakeCollectionRunner) RunCallCount() int {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return len(fake.runArgsForCall)
}

func (fake *FakeCollectionRunner) RunCalls(stub func(context.Context, collector.JobData, collector.CollectionRunnerOptions)) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = stub
}

func (fake *FakeCollectionRunner) RunArgsForCall(i int) (context.Context, collector.JobData, collector.CollectionRunnerOptions) {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	argsForCall := fake.runArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeCollectionRunner) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCollectionRunner) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ collector.CollectionRunner = new(FakeCollectionRunner)
