apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  type: NodePort
  ports:
  - name: management
    port: 15672
    targetPort: 15672
    nodePort: 31234
  - name: bus
    port: 5672
    targetPort: 5672
    nodePort: 30000
  - name: metrics
    port: 15692
    targetPort: 15692