apiVersion: v1
kind: Service
metadata:
  name: front
spec:
  type: NodePort
  selector:
    app: front
  ports:
    - name: front
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30050