apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front
          image: lca-front
          imagePullPolicy: Never
          resources:
            limits:
              memory: 512Mi
              cpu: "500m"
          env:
          - name: APP_NAME
            value: front