@startuml
actor Client as client
queue MQ as mq
participant Scheduler as scheduler
collections Collectors as collectors
database CollectionData as collectionData
client -> scheduler : POST trigger
Activate scheduler
scheduler -> collectionData : Create. Status 'created'
scheduler -> mq : Enqueue task
Deactivate scheduler
Activate mq
mq -> collectors : Fetch task
Deactivate mq
Activate collectors
collectors -> collectionData : Status 'running'
collectors -> collectionData : Status 'success' or 'fail'
Deactivate collectors
@enduml
