apiVersion: v1
kind: Service
metadata:
  name: ne
spec:
  type: NodePort
  selector:
    app: ne
  ports:
    - name: ne
      protocol: TCP
      port: 22
      targetPort: 22
      nodePort: 30022