apiVersion: v1
kind: Service
metadata:
  name: collector
spec:
  type: NodePort
  selector:
    app: collector
  ports:
    - name: collector
      protocol: TCP
      port: 3003
      targetPort: 3003
      nodePort: 30030