app:
  version: "0.1.0"
  name: cdg
  data-path: "./.temp/data"
http:
  port: 30020
rabbitmq:
  uri: amqp://127.0.0.1:30000
db:
  uri: "host=localhost user=postgres password=postgres dbname=lca port=30432 sslmode=disable"
