app:
  version: "0.1.0"
  name: cdg
  data-path: "/tmp/lca/data"
http:
  port: 30020
rabbitmq:
  uri: amqp://192.168.49.2:30000
db:
  uri: "host=192.168.49.2 user=postgres password=postgres dbname=cdg port=30432 sslmode=disable"
