app:
  version: "0.1.0"
  name: scheduler
  data-path: " "
http:
  port: 30010
rabbitmq:
  uri: amqp://192.168.49.2:30000
db:
  uri: "host=192.168.49.2 user=postgres password=postgres dbname=scheduler port=30432 sslmode=disable"