apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: db
  type: NodePort
  ports:
    - name: db
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30432