apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-store-data
spec:
  # assuming using rancher
  # if not change to name from 'kubectl get storageclass'
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi