apiVersion: v1
kind: PersistentVolume
metadata:
  name: file-store-pv
  labels:
    type: local
spec:
  # assuming using rancher
  # if not change to name from 'kubectl get storageclass'
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    type: DirectoryOrCreate
    path: "/mnt/data/lca/file-store/data"